language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
sudo: false
install:
    - cpanm --notest Archive::Zip || { cat ~/.cpanm/build.log ; false ; }
    - cpanm Dist::Zilla::App::Command::xtest || { cat ~/.cpanm/build.log ; false ; }
    - dzil authordeps --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
script:
    - dzil test --author --release
    - dzil xtest
